import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Sterling App",
  description: "Generated by sterling app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans bg-brand-black min-h-screen text-white selection:bg-brand-accent selection:text-white">
        <Navbar />
        <main className="fade-in">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
